import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sitemap-project",
  description: "Generated by create next app",
};

export type Pages = Record<string, `/${string}`>;
const defaultQueryString = "_limit=10&_page=1";

const pages: Pages = {
  home: "/",
  services: "/services",
  designs: "/designs",
  portfolio: "/portfolio",
  tools: "/tools",
  blogs: `/blogs?${defaultQueryString}`,
  contact: "/contact",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} "flex min-h-screen items-center justify-between p-24`}
      >
        <Navbar pages={pages} />
        <main className="flex justify-center mt-12">{children}</main>
      </body>
    </html>
  );
}
